### ISSUE TITLE
White screen when clicking on verify email link in different browser

### ISSUE THREAD

**Issue by TheAccountingStudio** [CalderaWP/verify-email-for-caldera-forms#3]
Great software - really appreciate!
However one bug - when clicking on the verify link in the email, if this opens a different browser to the browser that was used to originally submit the form, it gets stuck at a white screen.
So if one submits a link from PC and then verifies using phone it fails

**Comment by Shelob9** [comment]
Resolved via 	4dec79e
 Note this fix requires Caldera Forms 1.5 or later. Before that there was no way to recover from a failed nonce verification, which will never work cross browser.
